### ISSUE TITLE
fix: bounding box

### ISSUE THREAD

**Issue by dargmuesli** [Sec-ant/barcode-detector#1]
Hey, are you sure the bounding box is implemented correctly?
I'd expect 
![image](https://github.com/Sec-ant/barcode-detector/assets/4778485/58dc0c54-27b7-4182-a6cd-4990e9c81853)
but get
![image](https://github.com/Sec-ant/barcode-detector/assets/4778485/a9c5d46a-2281-4ca3-ad56-260702aea4fb)

**Comment by Sec-ant** [comment]
Hey, I accidentally typed `Math.min` when I want to use `Math.max`, can you try [v0.1.4](https://www.npmjs.com/package/@sec-ant/barcode-detector/v/0.1.4) to check whether it fixes this problem?

**Comment by dargmuesli** [comment]
It does! Thx :heart:
