### ISSUE TITLE
Module type declaration not found

### ISSUE THREAD

**Issue by cinob** [Sec-ant/barcode-detector#21]
When importing `barcode-detector/pure` or `barcode-detector/side-effects` ts warns that the module or its corresponding type declaration cannot be found.
I'm not sure if this is because of my local ts environment or something else.

**Comment by Sec-ant** [comment]
Can you share your repo or reproduce it in stackblitz or codepen?

**Comment by Sec-ant** [comment]
Not sure if this is related, but subpath import requires `Node16`, `NodeNext` or `Bundler` (I believe) as the `moduleResolution` in your `tsconfig`: https://github.com/microsoft/TypeScript/issues/44848#issuecomment-1212826554 

If the config looks good, sometimes you'll have to restart the ts server to clear its error messages, in vscode.

And if you are sure this is not a problem of this repo, would you close this issue?

**Comment by cinob** [comment]
Other third-party subpath packages I've used have normal type hints, and I've tried to configure [this](https://github.com/cinob/barcode-detector/commit/adcbc002181cea4ed03b1fd3bb90295983832b89) to make the subpath package type hints work.

**Comment by Sec-ant** [comment]
Thanks for your input.

`exports` field should be supported in TypeScript ^4.7, and it will automatically look for corresponding declaration files once it resolves the `.js` entry files: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#:~:text=The%20new%20support,types%22%20import%20condition.

So I don't think setting the declaration files path are necessary, and setting  `typesVersions` with es module `d.ts` paths seems strange because this is a dual module package which supports both es and cjs module at the same time.

If this error bothers you, please share me a reproducible repo so I can properly fix it.

**Comment by cinob** [comment]
All projects that directly import the 'barcode-detector/pure' package will report this error.
For example, in `vue-qrcode-reader` [here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/scanner.ts)

**Comment by Sec-ant** [comment]
Working fine on my side, what's your Typescript version?

![image](https://github.com/Sec-ant/barcode-detector/assets/10386119/c7534b74-a891-42ec-a445-1897a2478bd6)

**Comment by cinob** [comment]
5.2.2
![image](https://github.com/Sec-ant/barcode-detector/assets/30230686/849c5b8b-80a0-405c-8683-3bafcb303718)
Here's a [repo](https://github.com/cinob/barcode-detector-demo)

**Comment by Sec-ant** [comment]
I've made a PR in your repo to solve this issue. It's because nuxt is using `node` as the default `moduleResolution` strategy. `bundler` is recommended for future projects.

**Comment by cinob** [comment]
Thank you very much, this was solved nicely by setting `moduleResolution: bundler`

**Comment by Sec-ant** [comment]
@ollema Could you please provide a minimal setup so I can take a look?

**Comment by ollema** [comment]
> @ollema Could you please provide a minimal setup so I can take a look?

no need - this will be fixed in SvelteKit 2.0

**Comment by ollema** [comment]
just a heads up for any SvelteKit users that might stumble upon this thread - SvelteKit 2.0 was just released and now this package works great out of the box!
