### ISSUE TITLE
can i use this package for next js app?

### ISSUE THREAD

**Issue by SirojbekMaqsudov** [Sec-ant/barcode-detector#54]

**Comment by Sec-ant** [comment]
This package is intended to be used as a polyfill of the [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API) so it requires client-side web APIs like [DOMRectReadOnly](https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly) according to the [spec](https://wicg.github.io/shape-detection-api/#detectedbarcode-section). Therefore you cannot use this package on the server side.

If you need a more api-agnostic solution, have a look at [zxing-wasm](https://github.com/Sec-ant/zxing-wasm), which gives you more control over the barcode detection process and information from the detected result, and is also what this package uses under the hood.

**Comment by SirojbekMaqsudov** [comment]
thanks
