### ISSUE TITLE
can i config resolution camera device?

### ISSUE THREAD

**Issue by alptangal** [Sec-ant/barcode-detector#83]
my sample barcode not detected by camera, i though that trouble in resolution camera device received. cuz before i try capture  the barcode then zoom in it and plugin still working
hope hear more suggest from you

**Comment by Sec-ant** [comment]
I can't help you on how to properly setup the cameras. I suggest you check the doc first and ask more specific questions with some demo code in the discussions session: https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API
