### ISSUE TITLE
Can this library runs on Node.js ?

### ISSUE THREAD

**Issue by GreenFlag31** [Sec-ant/barcode-detector#89]
Hi, 

I have multiple times tried to make it work in a Node.js environnement but unsucessfully. There is a part in the readMe "Recommended Usage with Node + ESM", so is this possible?

If it's possible, can you provide a simple example?

Thanks in advance

**Comment by Sec-ant** [comment]
Hi, apologize for the late response.

This lib is meant to be used as a polyfill of the [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API), which is a Web API and requires other Web and DOM APIs like canvas, DOMRectReadOnly, etc. Unless they're also properly polyfilled (which may also introduce significant performance loss), this lib is not likely to be used in node.

> There is a part in the readMe "Recommended Usage with Node + ESM", so is this possible?

This is for building not running.

If you want to run barcode detections in other JS runtimes, you can check out the lower-level [zxing-wasm](https://github.com/Sec-ant/zxing-wasm) project this lib depends on, which also provides more control options.
