### ISSUE TITLE
Scanning the QR code yielded no response

### ISSUE THREAD

**Issue by coderwyd** [Sec-ant/barcode-detector#90]
**Describe the bug**
When I scanned the code through `vue-qrcode-reader`, I found that the lower version of Safari could not parse the QR code.

![image](https://github.com/user-attachments/assets/7d2f8d10-4486-44b6-9a56-93f63689e021)

- Device: iPhone7Plus
- OS: iOS13.6.1
- Browser: safari
- vue-qrcode-reader Version: v5.5.7

**Comment by Sec-ant** [comment]
Hi, sorry for the late response.

Maybe there are some APIs that are not supported. Unfortunately, I don't have a such device to reproduce the issue, would you mind helping me find the specific location where this error (`function is not a constructor`) is thrown?

**Comment by Sec-ant** [comment]
Closing this due to lack of response

**Comment by coderwyd** [comment]
Hello, I'm sorry for replying so late. I seem to have found the reason. There is a problem when using the EventTarget() constructor, [EventTarget()](https://caniuse.com/?search=EventTarget()), the api seems to only support safari14+, Maybe we can add a polyfill corresponding to EventTarget.

**Comment by coderwyd** [comment]
I tried adding a polyfill and found that the problem was solved. Is it possible to consider adding the corresponding polyfill directly to the library to improve compatibility?

**Comment by Sec-ant** [comment]
Glad to hear you find the problem. IMO API polyfills should be handled by the consumer, while the library itself should only focus on JS/WASM syntax compatibility.
